In [1]:
# this is a function
# it prints on our screen Hello George!
# you can recognise a function by the ( ) that follow after the name
# the input parameters are passed to the function in the parantheses 

print("Hello George!") 

Hello George!


In [2]:
# lets import a couple of python modules/packages
import math # math contains a number of useful math functiosn and constants
import numpy as np


In [3]:
# the value of pi is stored in a math variable

print(f"{math.pi:.24f}") 
print(f"{math.pi:.2}")


3.141592653589793115997963
3.1


In [4]:
# np.round() is a function with more than one input parameters
np.round(math.pi, 3)

3.142

In [5]:
# some function parameters can be specified by name at any position 
# this makes our code more readable
# here we specify that the result of the rounding should be placed back in the prices array

print (np.round(math.pi, decimals=2))



3.14


In [6]:
math.pi = 5 # Attention: do not change the value of constants by mistake
print(math.pi)

5


### How do we define a function?


we can define our own functions when we have tasks that we want to perform regulalry. 

<b>A function is a block of code that we will invoke at a later point.
It is not exectued at the location it is defined!</b>

In [7]:
# a function definition starts with the keyword def followed by the name of the function
# the input parameters are named in ()
# as with the if and loop constructs, the first line ends with :
# the block of code that belongs to the function follows in the next line and must be indented


def hello (name) :              # the function hello is defined with one parameter: name
    print(f"Hello {name}")      # name is used in the f string
    
    
    
hello("George")                 # in this code we call the function hello
                                # the string "George" is then assigned to the variable name 

Hello George


In [8]:
# a return statement may be used to return the result of a computation

def XandYsquare(x,y):    # this function takes two input parameters
    z = x + y**2
    return z             # and returns one value

print(XandYsquare(2,3))  # When the function is called, it is 'replaced' by the value it returns

11


In [9]:
# a function can return multiple values that are assinged to multiple variables

def funWithMultReturns(x):
    return 2*x, 3*x         # the multiple outputs are seperated by commas

In [10]:
a,b = funWithMultReturns(5) # when calling the function we use commas to seperate the variables too
print(a)
print(b)

10
15


### back to the wallet example!

In [11]:
wallet = 41
breakfast = np.array(['cinnamon bun', 'coffee', 'orange juice'])
prices = np.array([2,3.6,2.9])

In [12]:
# functions can 'see' the variables that are defined in the scrpit

# these variables are 'global'
def buy(item):
    print(f"I have €{wallet}.")
    print(f"I want a {breakfast[item]}.")
    print(f"Here is €{prices[item]:.2f}.")
    left_with = wallet - prices[item]

In [13]:
buy (0)

I have €41.
I want a cinnamon bun.
Here is €2.00.


In [14]:
# but variables defined within the function cannot be accessed from outside
print(left_with)

NameError: name 'left_with' is not defined

In [15]:
# although th global variables can be accessed, they cannot be changed from inside the function
# lets attempt to subtract the cost of the chosen item from our wallet

def buy(item):
    print(f"I have €{wallet}.")
    print(f"I want a {breakfast[item]}.")
    print(f"Here is €{prices[item]}.")
    wallet = wallet - prices[item]
    print(f"I am left with €{wallet}.")

In [17]:
# while the definition of the function does not produce an error 
# when calling the function we get an error
# as the global variable wallet cannot be changed
# python assumes that wallet inside the function is a new local variable
# however, wallet is not assinged an initial value and therefore 
# the price of the item cannot be subtracted from it

buy(0)

UnboundLocalError: local variable 'wallet' referenced before assignment

In [18]:
# we can go arround the problem by explicitly declaring that the variable wallet is the existing global variable.

def buy(item):
    global wallet                  
    print(f"I have €{wallet}.")
    print(f"I want a {breakfast[item]}.")
    print(f"Here is €{prices[item]}.")
    wallet = wallet - prices[item]
    print(f"I am left with €{wallet}.")
    
    
    
buy(0)
print(wallet)

I have €41.
I want a cinnamon bun.
Here is €2.0.
I am left with €39.0.
39.0


#### How about the input parameters? 
#### Can they be changed inside a function? 
#### Will these changes be reflected back to the global variables?
#### Python has a unique answer to this questions!

In [19]:
# consider the following function 
def increase_prices(p, r):
    v =  p * r
    p = p + v 
    return p

print(increase_prices(prices,.25))
print(prices) # was the value of the original array changed?

[2.5   4.5   3.625]
[2.  3.6 2.9]


In [20]:
# now try this definition
def increase_prices(p, r):
    v =  p * r
    p += v
    return p

print(increase_prices(prices,.25))
print(prices) # was the value of the original array changed?

[2.5   4.5   3.625]
[2.5   4.5   3.625]


### here is the explanation of the <i>paradox</i>!

To understand the difference between the two function definitions above we must first understand what variables are in python!

Variables are like containers for ojects. An array is such an object.

The variables are <b><u>not</u></b> the objects. They only contain them! 

When a variable is passed as an input parameter to a function, what is actually given to the function  is the object contained in the variable. 

The function then has its own container (its own variable) to hold the object for as long the function is running.

In our example, the variable <code>prices</code> contains an array which is passed to the function <code>inrease_prices</code>. The function then takes the array and puts it in its own variable <code>p</code>.

In our first try, we tried to alter the array using <code> p = p + v </code>.

<code> p + v </code> adds the two arrays and creates a new array for the result. The two arrays in the variables <code>p</code> or <code>v</code> are not modified... as expected! 

Then, the assingment operator <code>=</code> puts the newly created array into the variable <code>p</code>, throwing out of the container the array that was previously found there. 

Therefore, the initial array contained in <code>prices</code> is left unchanged, and <code>p</code> contains a new array.


But what is going on in the second function definition?

In the second definition, we use the <code> += </code> operator to do the same operation (add the two arrays).

However, this operator just adds the elements of the array in <code>v</code> at thee end of array  <code>p</code>. It does not create a new array!

The array in <code>p</code> is the same array found in <code>prices</code>. 



Python's approach to passing parameters to functions is called <i><b>pass-by-object-reference</b></i> and it is rather unique. More common approaches used in other languages are <i>pass-by-reference</i> and <i>pass-by-value</i>.
</span>