In [1]:
# NumPy is a python package that has to be imported in each notebook we want to use it
# it is common practice when importing a package in python to assing it an alias 
# in this notebook, we import the NumPy package and we refer to it as np 


import numpy as np

In [2]:
# to access the functions, objects etc included in the NumPy package we use 'np.*'

# lets create two arrays
breakfast = np.array(['cinnamon bun', 'coffee', 'tomato juice']) # breakfast because stores the names of various the breakfast items
prices = np.array([2,3.6,2.9]) #prices stores the price of each item

In [3]:
# the two arrays are ordered so that there is a 1 to 1 correpsondence between their elements. 
print(breakfast)
print(prices)

['cinnamon bun' 'coffee' 'tomato juice']
[2.  3.6 2.9]


In [4]:
# to access specific elements of an array use []
print(breakfast[1])

coffee


In [5]:
print(breakfast[0])

cinnamon bun


In [6]:
# we can go through all the elements of an array using a 'for loop'

# the bock of code that belogns in loops (or other structures) id defined 
# by "alinging" the lines under the for statement 

for br in breakfast:  # the first line of a structure (loops, ifs or functions) always ends with :
    print(br)

cinnamon bun
coffee
tomato juice


In [7]:
# we can use the range function to generate a sequence of numbers
for i in range(0,breakfast.size):
    print(breakfast[i])
    print(prices[i])

cinnamon bun
2.0
coffee
3.6
tomato juice
2.9


In [8]:
for i in range(0,breakfast.size):
    print(f"{breakfast[i]} for €{prices[i]:.2f}")

cinnamon bun for €2.00
coffee for €3.60
tomato juice for €2.90


In [9]:
# NumPy arrays come with functions
# for instance, we can calculate the sum of the elements of an array:

total_cost = prices.sum()

In [10]:
# if I have €3, which breakfast items can I buy?

wallet = 3

for i in range(0,breakfast.size): #see also np.arange() and np.linspace()
    if wallet >= prices[i]:
        print(f"I have enough money for a {breakfast[i]}")

I have enough money for a cinnamon bun
I have enough money for a tomato juice


In [11]:
# for loops can be used to create lists
which_Items_canIbuy = [wallet>p for p in prices]
print(which_Items_canIbuy)

[True, False, True]


In [12]:
type(which_Items_canIbuy)

list

In [13]:
# and we can easily convert lists into numpy arrays
which_Items_canIbuy = np.asarray(which_Items_canIbuy)
print(which_Items_canIbuy)
type(which_Items_canIbuy)

[ True False  True]


numpy.ndarray

In [14]:
# we can do mathematical operations with arrays

# for instace, we might want to add a service fee to all the rpcies

prices = prices + .25 # add a value to all elements of the array

In [15]:
print(prices)

[2.25 3.85 3.15]


In [16]:
# lets say that the prices went up!

price_raise = prices * 0.25 # or multiply them by a factor (e.g. 25%)

In [17]:
# we can do mathematical operations between the elements of arrays

prices = prices + price_raise # e.g. add the increase of the prices to the initial prices and update th array

In [18]:
print(price_raise)
print(prices)

[0.5625 0.9625 0.7875]
[2.8125 4.8125 3.9375]


In [19]:
# another useful NumPy function:

print(np.round(prices, 2)) # this rounds the values to the second decimal place 

[2.81 4.81 3.94]


In [20]:
print(prices)

# some function parameters can be specified by name and not necessarily at the right position 
# this makes our code more readable
# here we specify that the result of the rounding should be placed back in the prices array

np.round(prices, out = prices, decimals=2) 

print(prices)

[2.8125 4.8125 3.9375]
[2.81 4.81 3.94]


In [21]:
# alternatively we could invoke the function like this
print(prices.round(decimals = 1))


[2.8 4.8 3.9]


We can check if an element is in an array using the <code> in </code> operator.

In fact <code> in </code> will work for many other variables, not only numpy arrays!

In [22]:
print ("coffee" in breakfast)

True


In [23]:
print ("banana" in breakfast)

False


In [24]:
print ("Coffee" in breakfast) # the comparison is case sensitive!

False
